accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.RegistrationView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

catalogue/urls.py
from django.urls import path

from . import views


app_name = 'catalogue'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='list'),
    path('create/', views.ProductCreateView.as_view(), name='product-create'),
    path('<product_code>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('<product_code>/edit/', views.ProductUpdateView.as_view(), name='product-update'),
    path('<product_code>/delete/', views.ProductDeleteView.as_view(), name='product-delete')
]

shopping_cart/urls.py
from django.urls import path

from . import views


app_name = 'shopping_cart'

urlpatterns = [
    path('get-items/', views.GetItemsView.as_view(), name='get-items'),
    path('add-item/', views.AddItemView.as_view(), name='add-item'),
    path('remove-item/', views.RemoveItemView.as_view(), name='remove-item')
]

webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogue.urls')),
    path('account/', include('accounts.urls')),
    path('cart/', include('shopping_cart.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Blank
        {% endblock %}
    </title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>

    <div id="x-data" x-data="{ cartOpen: false , isOpen: false }" class="bg-white">
        <style>
            [x-cloak] { display: none }
        </style>

        <div class="flex flex-col h-screen justify-between">
            <header>
                <div class="container mx-auto px-6 py-3">
                    {% include 'navbar.html' %}

                    {% block header %}
                    {% endblock %}
                </div>
            </header>

            <main class="container mx-auto px-6 py-3">
                {% block content %}
                {% endblock %}
            </main>

            <div class="flex-1"></div>

            <footer>
                {% include 'footer.html' %}
            </footer>
        </div>

        {% if user.is_authenticated %}
            {% include 'cart.html' %}
        {% endif %}
    </div>

</body>
</html>

templates/cart.html
<script>
    // Getting a specific cookie
    function getCookie(name) {
        let cookieValue = null;

        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }

        return cookieValue;
    }

    // Displaying items in the shopping cart
    let displayItems = (items) => {
        let items_tag = document.querySelector('#items')
        let checkout_tag = document.querySelector('#checkout')

        items_tag.innerHTML = ""

        if (items.length) {
            checkout_tag.classList.remove('hidden')
            let total_price = 0

            items.forEach(item => {
                items_tag.insertAdjacentHTML('beforeend',
                    `
                    <div class="flex justify-between mt-6">
                        <div class="flex">
                            <img class="h-20 w-20 object-cover rounded" src="${item['image']}" alt="">
                            <div class="mx-3">
                                <h3 class="text-sm text-gray-600">${item['title']}</h3>
                                <div class="flex items-center mt-2">
                                    <button onclick="addItemToCart(${item['product_id']})" class="text-gray-500 focus:outline-none focus:text-gray-600">
                                        <svg class="h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                    </button>
                                    <span class="text-gray-700 mx-2">${item['quantity']}</span>
                                    <button onclick="removeItemFromCart(${item['product_id']})" class="text-gray-500 focus:outline-none focus:text-gray-600">
                                        <svg class="h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <span class="text-gray-600">${item['price'] * item['quantity']} €</span>
                    </div>
                    `)
                total_price += item['price'] * item['quantity']
            })

            items_tag.insertAdjacentHTML('beforeend',
                `<p class="text-md text-gray-700 my-4">Total: ${total_price} €</p>`
            )

        } else {
            checkout_tag.classList.add('hidden')

            items_tag.insertAdjacentHTML('beforebegin',
                `<p class="text-md text-gray-700">Nothing here yet</p>`
            )
        }
    }

    // Refreshing shopping cart
    async function refreshItems() {
        let response = await fetch('{% url 'shopping_cart:get-items' %}')
        let data = await response.json()

        displayItems(data['items'])
    }

    // Adding an item to the shopping cart
    let addItemToCart = (productId) => {
        fetch('{% url 'shopping_cart:add-item' %}', {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': getCookie('csrftoken')
            },
            body: JSON.stringify({'product_id': productId})
        }).then(() => refreshItems())

        let xData = document.querySelector("#x-data")
        xData.setAttribute('x-data', '{ cartOpen: true , isOpen: true }')

    }

    // Removing an item from the shopping cart
    let removeItemFromCart = (productId) => {
        fetch('{% url 'shopping_cart:remove-item' %}', {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': getCookie('csrftoken')
            },
            body: JSON.stringify({'product_id': productId})
        }).then(() => refreshItems())
    }

    // Receive and display items in the shopping cart when page is loaded
    window.onload = refreshItems
</script>

<!-- Shopping cart -->
<div x-cloak :class="cartOpen ? 'translate-x-0 ease-out' : 'translate-x-full ease-in'" class="fixed right-0 top-0 max-w-xs w-full h-full px-6 py-4 transition duration-300 transform overflow-y-auto bg-white border-l-2 border-gray-300" style="z-index: 999">

    <!-- Your cart -->
    <div class="flex items-center justify-between">
        <h3 class="text-2xl font-medium text-gray-700">Your cart</h3>
        <button @click="cartOpen = !cartOpen" class="text-gray-600 focus:outline-none">
            <svg class="h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M6 18L18 6M6 6l12 12"></path></svg>
        </button>
    </div>
    <hr class="my-3">

    <!-- Items -->
    <div id="items" class="w-full"></div>

    <!-- Checkout -->
    <button onclick="alert('Checkout is not available, because this shop is not real :)')" id="checkout" class="flex items-center justify-center mt-4 px-3 py-2 bg-blue-600 text-white text-sm uppercase font-medium rounded hover:bg-blue-500 focus:outline-none focus:bg-blue-500">
        <span>Checkout</span>
        <svg class="h-5 w-5 mx-2" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
    </button>
</div>

templates/footer.html
<div class="container mx-auto px-6">
    <div class="mt-10 border-t-2 border-gray-300 flex flex-col items-center">
        <div class="sm:w-2/3 text-center py-6">
            <p class="text-sm text-gray-700 font-bold mb-2">
                © 2021 by Adrian Kalinin
            </p>
        </div>
    </div>
</div>

templates/navbar.html
<div class="flex items-center justify-between">

    <div class="hidden w-full text-gray-600 md:flex md:items-center">
        <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M16.2721 10.2721C16.2721 12.4813 14.4813 14.2721 12.2721 14.2721C10.063 14.2721 8.27214 12.4813 8.27214 10.2721C8.27214 8.06298 10.063 6.27212 12.2721 6.27212C14.4813 6.27212 16.2721 8.06298 16.2721 10.2721ZM14.2721 10.2721C14.2721 11.3767 13.3767 12.2721 12.2721 12.2721C11.1676 12.2721 10.2721 11.3767 10.2721 10.2721C10.2721 9.16755 11.1676 8.27212 12.2721 8.27212C13.3767 8.27212 14.2721 9.16755 14.2721 10.2721Z" fill="currentColor"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M5.79417 16.5183C2.19424 13.0909 2.05438 7.39409 5.48178 3.79417C8.90918 0.194243 14.6059 0.054383 18.2059 3.48178C21.8058 6.90918 21.9457 12.6059 18.5183 16.2059L12.3124 22.7241L5.79417 16.5183ZM17.0698 14.8268L12.243 19.8965L7.17324 15.0698C4.3733 12.404 4.26452 7.97318 6.93028 5.17324C9.59603 2.3733 14.0268 2.26452 16.8268 4.93028C19.6267 7.59603 19.7355 12.0268 17.0698 14.8268Z" fill="currentColor" />
        </svg>
        <span class="mx-1 text-sm">Helsinki</span>
    </div>

    <div class="w-full text-gray-700 md:text-center text-2xl font-semibold">
        <a href="/">Webshop</a>
    </div>

    <div class="flex items-center justify-end w-full">

        {% if user.is_authenticated %}
            {% if user.is_staff %}
                <a href="{% url 'catalogue:product-create' %}" class="text-gray-500 hover:text-gray-700 flex items-center mr-6">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 sm:h-5 sm:w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd"></path>
                    </svg>
                    <span class="ml-1 text-sm sm:text-base">Add a product</span>
                </a>
            {% endif %}

            <button @click="cartOpen = !cartOpen" class="text-gray-600 focus:outline-none">
                <svg class="h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                    <path d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path>
                </svg>
            </button>
            <h5 class="text-gray-700 text-sm sm:text-base ml-2">Welcome, {{ user.first_name }}!</h5>
            <a href="{% url 'accounts:logout' %}" class="text-sm sm:text-base text-gray-500 hover:text-gray-700 ml-3">Logout</a>

        {% else %}
            <a href="{% url 'accounts:login' %}" class="text-base sm:text-xl text-gray-500 hover:text-gray-700">Login</a>
            <a href="{% url 'accounts:signup' %}" class="text-base sm:text-xl text-gray-500 hover:text-gray-700 ml-4">Sign Up</a>
        {% endif %}

    </div>
</div>

templates/search.html
<!-- Search -->
<div class="relative mt-6 max-w-lg mx-auto">
    <span class="absolute inset-y-0 left-0 pl-3 flex items-center">
        <svg class="h-5 w-5 text-gray-500" viewBox="0 0 24 24" fill="none">
            <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
        </svg>
    </span>
    <label>
        <input class="w-full border rounded-md pl-10 pr-4 py-2 focus:border-blue-500 focus:outline-none focus:shadow-outline" type="text" placeholder="Search" name="q" value="{% if search_value %}{{ search_value }}{% endif %}">
    </label>
</div>