catalogue/urls.py
from django.urls import path

from . import views


app_name = 'catalogue'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='list'),
    path('create/', views.ProductCreateView.as_view(), name='product-create'),
    path('<product_code>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('<product_code>/edit/', views.ProductUpdateView.as_view(), name='product-update'),
    path('<product_code>/delete/', views.ProductDeleteView.as_view(), name='product-delete')
]

webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogue.urls')),
    path('account/', include('accounts.urls')),
    path('cart/', include('shopping_cart.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogue/models.py
from django.db import models


class Product(models.Model):
    product_code = models.CharField(max_length=10, editable=False, null=True, unique=True)
    title = models.CharField(max_length=80)
    description = models.TextField(blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=12)
    image = models.ImageField(upload_to='images/')

    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.product_code = f'{self.id:5}'.replace(' ', '0')
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title} ({self.product_code})'

catalogue/forms.py
from django import forms

from .models import Product


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'image']

catalogue/views.py
from django.shortcuts import reverse
from django.views import generic
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q

from .models import Product
from .forms import ProductModelForm


class ProductListView(generic.ListView):
    template_name = 'catalogue/product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        queryset = Product.objects.all()

        if query := self.request.GET.get('q'):
            queryset = queryset.filter(Q(title__icontains=query) | Q(product_code__exact=query))

        sort_value = self.request.GET.get('sort') or '-created_at'

        return queryset.order_by(sort_value)

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super(ProductListView, self).get_context_data(**kwargs)
        context_data['search_value'] = self.request.GET.get('q')
        context_data['sort_value'] = self.request.GET.get('sort')
        return context_data


class ProductDetailView(generic.DetailView):
    template_name = 'catalogue/product_detail.html'
    context_object_name = 'product'

    def get_object(self, queryset=None):
        product_code = self.kwargs.get('product_code')
        return Product.objects.get(product_code=product_code)


class ProductCreateView(PermissionRequiredMixin, generic.CreateView):
    template_name = 'catalogue/product_create.html'
    form_class = ProductModelForm
    permission_required = 'catalogue.add_product'

    def get_success_url(self):
        return reverse('catalogue:list')


class ProductUpdateView(PermissionRequiredMixin, generic.UpdateView):
    template_name = 'catalogue/product_update.html'
    form_class = ProductModelForm
    permission_required = 'catalogue.change_product'

    def get_object(self, queryset=None):
        pc = self.kwargs.get('product_code')
        return Product.objects.filter(product_code=pc).first()

    def get_success_url(self):
        return reverse('catalogue:product-detail', kwargs={'product_code': self.kwargs.get('product_code')})


class ProductDeleteView(PermissionRequiredMixin, generic.DeleteView):
    template_name = 'catalogue/product_delete.html'
    permission_required = 'catalogue.delete_product'

    def get_object(self, queryset=None):
        pc = self.kwargs.get('product_code')
        return Product.objects.filter(product_code=pc).first()

    def get_success_url(self):
        return reverse('catalogue:list')

catalogue/templates/catalogue/product_create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
    New Product
{% endblock %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <h1 class="text-4xl text-gray-800 my-5">Add a product</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 border-0 py-2 px-8 rounded-md mt-4">Submit</button>
        </form>
    </div>
{% endblock %}

catalogue/templates/catalogue/product_delete.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
    {{ product.title }} ({{ product.productcode }})
{% endblock %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <h1 class="text-2xl text-gray-800 mt-12 mb-7">Are you sure you want to delete "{{ product.title }}" ({{ product.product_code }})?</h1>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="text-white text-center bg-red-500 hover:bg-red-600 rounded-md border-0 py-2 px-8">Delete</button>
        </form>
    </div>
{% endblock %}

catalogue/templates/catalogue/product_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ product.title }}
{% endblock %}

{% block header %}
    {% include 'search.html' %}
{% endblock %}

{% block content %}
    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-12 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">

                <div class="w-full mb-6">
                    <a href="{% url 'catalogue:list' %}" class="flex items-center ">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
                        </svg>
                        <p class="md:text-lg ml-2">Back to Catalogue</p>
                    </a>
                </div>

                <img class="lg:w-1/2 h-full lg:w-auto object-cover object-center rounded" alt=""
                     src="{{ MEDIA_URL }}{{ product.image.url }}">
                <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{ product.title }}</h1>

                    {% if product.description %}
                        <p class="leading-relaxed mt-6 mb-2">{{ product.description }}</p>
                    {% endif %}
                    <p class="leading-relaxed text-gray-400 mb-6">Product Code: {{ product.product_code }}.</p>

                    <div class="flex">
                        <span class="title-font font-medium text-2xl text-gray-900">{{ product.price }} €</span>
                        <button onclick="addItemToCart({{ product.id }})" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                            Add to cart
                        </button>
                    </div>

                    {% if user.is_staff %}
                        <div class="flex mt-6">
                            <a href="{% url 'catalogue:product-update' product.product_code %}" class="bg-transparent hover:bg-indigo-500 text-indigo-500 font-medium hover:text-white py-2 px-6 border border-indigo-500 hover:border-transparent rounded mr-5">Edit</a>
                            <a href="{% url 'catalogue:product-delete' product.product_code %}" class="bg-transparent hover:bg-red-500 text-red-500 font-medium hover:text-white py-2 px-6 border border-red-500 hover:border-transparent rounded mr-5">Delete</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

catalogue/templates/catalogue/product_list.html
{% extends 'base.html' %}

{% block title %}
    Catalogue
{% endblock %}

{% block header %}
    <form action="{% url 'catalogue:list' %}" method="get">
        {% include 'search.html' %}

        {% if products %}
             <div class="relative inline-flex items-center mt-8">
                <svg class="w-2 h-2 absolute top-0 left-36 m-4 pointer-events-none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 412 232"><path d="M206 171.144L42.678 7.822c-9.763-9.763-25.592-9.763-35.355 0-9.763 9.764-9.763 25.592 0 35.355l181 181c4.88 4.882 11.279 7.323 17.677 7.323s12.796-2.441 17.678-7.322l181-181c9.763-9.764 9.763-25.592 0-35.355-9.763-9.763-25.592-9.763-35.355 0L206 171.144z" fill="#648299" fill-rule="nonzero"></path></svg>
                <select name="sort" class="border border-gray-300 rounded-full text-gray-600 h-10 pl-5 pr-10 bg-white hover:border-gray-400 focus:outline-none appearance-none">
                    <option value="" {% if not sort_value %}selected{% endif %}>Sort by</option>
                    <option value="title" {% if sort_value == 'title' %}selected{% endif %}>A-Z</option>
                    <option value="-title" {% if sort_value == '-title' %}selected{% endif %}>Z-A</option>
                    <option value="price" {% if sort_value == 'price' %}selected{% endif %}>Price: low to high</option>
                    <option value="-price" {% if sort_value == '-price' %}selected{% endif %}>Price: high to low</option>
                </select>
                <button type="submit" class="ml-4 text-gray-500 hover:text-gray-900">Apply</button>
            </div>
        {% endif %}
    </form>
{% endblock %}

{% block content %}

        {% if products %}
            <div class="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 md:grid-cols-3 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
                {% for product in products %}
                    <div class="group relative">
                        <div class="w-full min-h-80 bg-gray-200 aspect-w-1 aspect-h-1 rounded-md overflow-hidden group-hover:opacity-75 lg:h-80 lg:aspect-none">
                            <img src="{{ MEDIA_URL }}{{ product.image.url }}" alt="{{ product.title }}"
                                 class="w-full h-full object-center object-cover lg:w-full lg:h-full">
                        </div>
                        <div class="mt-4 flex justify-between">
                            <div>
                                <h3 class="text-sm text-gray-700">
                                    <a href="{% url 'catalogue:product-detail' product.product_code %}">
                                        <span aria-hidden="true" class="absolute inset-0"></span>
                                        {{ product.title }}
                                    </a>
                                </h3>
                            </div>
                            <p class="text-sm font-medium text-gray-900">
                                {{ product.price }} €
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>

        {% else %}
            <div class="w-full flex flex-col mt-8">
                <h1 class="mx-auto text-gray-900 text-3xl title-font font-medium mb-4">Nothing matches your search</h1>
                <p class="mx-auto text-gray-500 text-xl">But don't give up – check the spelling or try less specific search terms.</p>
            </div>
        {% endif %}

{% endblock %}

catalogue/templates/catalogue/product_update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
    {{ product.title }} ({{ product.productcode }})
{% endblock %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <h1 class="text-4xl text-gray-800 my-5">{{ product.title }} ({{ product.product_code }})</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 border-0 py-2 px-8 rounded-md mt-4">Submit</button>
        </form>
    </div>
{% endblock %}